language: go

go:
  - "1.10"

git:
  depth: 10

branches:
  only:
    - master

install:
  - snap install hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  repo: https://github.com/cloudevents/cloudevents.github.io.git
  target-branch: master
  on:
    branch: master
