baseURL = "https://cloudevents.io"
languageCode = "en-us"
title = "CloudEvents"
theme = "hugo-theme-lean-launch-page"
canonifyurls = true
paginate = 3

googleAnalytics = ""

[params]
tagline = "A specification for describing event data in a common way"
# mailchimpURL = "//my-account.mailchimp.com/my-subscriber-url"
groupsiourl = "https://lists.cncf.io/g/cncf-cloudevents/signup?u=2254653446843417778"
groupsioid = "2254653446843417778"
icon = "cloudevents.png"

# twitter = "https://twitter.com/MyNewProduct"
# facebook = "https://facebook.com/MyNewProduct"
# instagram = "https://instragram.com/MyNewProduct"
# googleplus = "https://plus.google.com/+MyNewProduct"
github = "https://github.com/cloudevents/spec"
